version: '2.3'

services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    image: igt-lingspam/jupyter:latest
    container_name: igt_lingspam_jupyter
    volumes:
      - ./data:/experiments/data
      - ./notebooks:/experiments/notebooks
    entrypoint: "bash -c 'jupyter lab --no-browser --ip=0.0.0.0 --port=8877 --allow-root'"
    ports:
      - "8877:8877"